function [Subject,Gender,Age,Weight,Height,ActivityLevel] = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [Subject,Gender,Age,Weight,Height,ActivityLevel] = IMPORTFILE1(FILE)
%   reads data from the first worksheet in the Microsoft Excel spreadsheet
%   file named FILE and returns the data as column vectors.
%
%   [Subject,Gender,Age,Weight,Height,ActivityLevel] =
%   IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   [Subject,Gender,Age,Weight,Height,ActivityLevel] =
%   IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [Subject,Gender,Age,Weight,Height,ActivityLevel] = importfile1('ProjectEx1.xlsx','Sheet1',2,11);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/11/30 14:10:12

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 11;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,6]);
raw = raw(:,[1,3,4,5]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Subject = data(:,1);
Gender = cellVectors(:,1);
Age = data(:,2);
Weight = data(:,3);
Height = data(:,4);
ActivityLevel = cellVectors(:,2);

